### ISSUE TITLE
false statement 

### ISSUE THREAD

**Issue by logemann** [bbilger/jrestless-examples#14]
Hi,

your statement "Since a cognito user pool cannot be created with serverless or rather CloudFormation, one has to be created manually." is a bit outdated right? This is possible actually.

**Comment by bbilger** [comment]
@logemann
You might be right that it's supported by now.
I'll look into it when I find some time and update the documentation accordingly.

**Comment by logemann** [comment]
Its always tough to keep the old stuff "up to date" ;-)
