### ISSUE TITLE
File type with AWS Gateway Binary

### ISSUE THREAD

**Issue by klebermagno** [bbilger/jrestless-examples#8]
Hello,
I think that your project jrestless is wonderful and is exactly what I need.
I'm try to use the AWS Gateway Binary but I see that is return a inputstream but I need the file name and the file type.  
So I have a question. Can the rest receive a File and not a InputStream ?

**Comment by bbilger** [comment]
Hi @klebermagno ,
No, you cannot receive a "File object". What you can do is the following, assuming you want to upload a file using an HTML formular:
```java
@POST
@Path("/upload")
@Consumes(MediaType.MULTIPART_FORM_DATA)
public void uploadFile(@FormDataParam("file") InputStream uploadedInputStream,
                       @FormDataParam("file") FormDataBodyPart body) {
  LOG.info("file name: {}", body.getContentDisposition().getFileName());
  LOG.info("file type: {}", body.getMediaType());
  LOG.info("file contents: {}", new String(toByteArray(uploadedInputStream), StandardCharsets.UTF_8));
}
```
I extended the [aws-gateway-binary](https://github.com/bbilger/jrestless-examples/tree/master/aws/gateway/aws-gateway-binary) example to illustrate this. Check the [commit](https://github.com/bbilger/jrestless-examples/commit/9696458324f75620317c93e8a5a305fd4f5f41f8) for details.

Please note, however, that using binary with API Gateway has some limitations (those are limitations by API Gateway and not JResteless):
1. You need to register all binary media types, else you'll see base64 encoded content.
2. There's a limit of 10MB

And in case you are using the serverless framework for deployment: there's no way to set the binary media types, directly => that's a manual step.

**Comment by bbilger** [comment]
closing; assuming fixed
