### ISSUE TITLE
Stack traces with aws-gateway-cdi

### ISSUE THREAD

**Issue by dasniko** [bbilger/jrestless-examples#9]
Hi,

first of all - `jrestless` is a nice project! Thanks for doing this. :-)

I tried to run the `aws-gateway-cdi` example in my AWS account, but I'm getting a huge log output and lots of stack traces. Locally it's no problem, everything works as expected.
I'm encountering similar behaviour when running another Jersey impl. (https://github.com/serverlessbuch/lambda-jaxrs-cdi) with Weld on Lambda. However, I'm a bit of stuck...

Did you get your example running?
Are there some special configs I need to set?

**Comment by dasniko** [comment]
WTF is going on here?
Seems like I opened the issue too early, sorry.

When building and packaging with `maven`, this aweful logs and stack traces occur and the lambda responds with an internal error.
When building with `gradle`, everything works like expected...
So, _wtf_?

Anyway, do you have some ideas why this occurs?

**Comment by bbilger** [comment]
Hi @dasniko ,
Thanks for your feedback and sorry but I mainly use gradle.
Creating an uber-jar with maven is kind of tricky for Jersey, CDI/Weld, etc. :/ already had some fun with that (bbilger/jrestless#14)
After quite some testing and researching I think the issue can be solved by adding
```XML
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee" bean-discovery-mode="annotated" version="1.1"/>
```
to `src/main/resources/META-INF/beans.xml`
To me it looks like Weld discovers non-annotated classes as beans in the uber-jar created with the maven shade plugin - most likely some internal weld classes. The Weld documentation is talking about it, too: http://weld.cdi-spec.org/documentation/#5 but just excluding "org.jboss.weld.**" didn't work for whatever reason.

Let me know if this works. Will commit the fix shortly.

**Comment by dasniko** [comment]
Thanks for quick anwering, @bbilger ,
but no, doesn't work :-(
Additionally my tests are failing now during build.
Will investigate further and will give you feedback as soon I find a solution!
(However, I'm glad to know that it work with Gradle)

**Comment by bbilger** [comment]
Hi @dasniko 
when adjusting the beans.xml as suggested, you have to annotate your BooksController with @javax.enterprise.context.RequestScoped or ApplicationScoped (which is recommended, anyways and ensures that it's managed by the CDI container) and add 
```XML
<transformers>
  <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
</transformers>
```
to the maven shade plugin's configuration section (see https://github.com/bbilger/jrestless-examples/blob/master/pom.xml#L56)

Hope this helps

BTW: _serverlessbuch_ sounds interesting. Will the focus be on Java?

**Comment by dasniko** [comment]
Hey, this does the trick!
Thank you very, very much for your help.

So, we have
- `beans.xml` with above mentioned content
- `@RequestScoped` or `@ApplicationScoped` annotations at controller classes
- `extend the `maven-shade-plugin` configuration with the above mentioned `transformers` section.

[serverlessbuch.de](http://serverlessbuch.de) (german language) will focus on _serverless_ in general, based on AWS Lambda/API Gateway/DynamoDB with examples in Java and JavaScript. Hopefully, it will be published in autumn.
If it's ok for you, I'll mention your `jrestless` project!?

**Comment by bbilger** [comment]
Hi @dasniko ,
Glad to hear that it works, now!

Sure, I would be pleased to see JRestless being mentioned in your book.
